/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package girujan.snakesandladders;


import javax.swing.ImageIcon;

/**
 *
 * @author girujan
 */
public class DiceRoll extends javax.swing.JFrame {

    /**
     * Creates new form DiceRoll
     */
    int randomOne, randomTwo;
    ImageIcon ii;
    public DiceRoll() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subHeadOne = new javax.swing.JLabel();
        subHeadTwo = new javax.swing.JLabel();
        p1Dice = new javax.swing.JLabel();
        p2Dice = new javax.swing.JLabel();
        p1Roll = new javax.swing.JButton();
        p2Roll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        subHeadOne.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        subHeadOne.setText("Player One");

        subHeadTwo.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        subHeadTwo.setText("Player Two");

        p1Dice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/diceOne.png"))); // NOI18N

        p2Dice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/diceOne.png"))); // NOI18N

        p1Roll.setText("Roll");
        p1Roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1RollActionPerformed(evt);
            }
        });

        p2Roll.setText("Roll");
        p2Roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2RollActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subHeadOne)
                            .addComponent(p1Dice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(p1Roll, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subHeadTwo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(p2Roll, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p2Dice))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subHeadOne)
                    .addComponent(subHeadTwo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p1Dice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p2Dice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1Roll)
                    .addComponent(p2Roll))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p1RollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1RollActionPerformed
        // TODO add your handling code here:
        randomOne = (int) Math.ceil(Math.random()*6);
        System.out.println(randomOne);
        switch(randomOne){
            case 1:
                ii = new ImageIcon(getClass().getResource("/res/diceOne.png"));
                p1Dice.setIcon(ii);
                System.out.println(ii);
                break;
            case 2:
                ii = new ImageIcon(getClass().getResource("/res/diceTwo.png"));
                p1Dice.setIcon(ii);
                System.out.println(ii);
                break;
            case 3:
                ii = new ImageIcon(getClass().getResource("/res/diceThree.png"));
                p1Dice.setIcon(ii);
                System.out.println(ii);
                break;
            case 4:
                ii = new ImageIcon(getClass().getResource("/res/diceFour.png"));
                p1Dice.setIcon(ii);
                System.out.println(ii);
                break;
            case 5:
                ii = new ImageIcon(getClass().getResource("/res/diceFive.png"));
                p1Dice.setIcon(ii);
                System.out.println(ii);
                break;
            case 6:
                ii = new ImageIcon(getClass().getResource("/res/diceSix.png"));
                p1Dice.setIcon(ii);
                System.out.println(ii);
                break;
        }
    }//GEN-LAST:event_p1RollActionPerformed

    private void p2RollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2RollActionPerformed
        // TODO add your handling code here:
        randomTwo = (int)Math.ceil(Math.random()*6);
        System.out.println(randomTwo);
        switch(randomOne){
            case 1:
                ii = new ImageIcon(getClass().getResource("/res/diceOne.png"));
                p2Dice.setIcon(ii);
                System.out.println(ii);
                break;
            case 2:
                ii = new ImageIcon(getClass().getResource("/res/diceTwo.png"));
                p2Dice.setIcon(ii);
                System.out.println(ii);
                break;
            case 3:
                ii = new ImageIcon(getClass().getResource("/res/diceThree.png"));
                p2Dice.setIcon(ii);
                System.out.println(ii);
                break;
            case 4:
                ii = new ImageIcon(getClass().getResource("/res/diceFour.png"));
                p2Dice.setIcon(ii);
                System.out.println(ii);
                break;
            case 5:
                ii = new ImageIcon(getClass().getResource("/res/diceFive.png"));
                p2Dice.setIcon(ii);
                System.out.println(ii);
                break;
            case 6:
                ii = new ImageIcon(getClass().getResource("/res/diceSix.png"));
                p2Dice.setIcon(ii);
                System.out.println(ii);
                break;
        }
    }//GEN-LAST:event_p2RollActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiceRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiceRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiceRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiceRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiceRoll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel p1Dice;
    private javax.swing.JButton p1Roll;
    private javax.swing.JLabel p2Dice;
    private javax.swing.JButton p2Roll;
    private javax.swing.JLabel subHeadOne;
    private javax.swing.JLabel subHeadTwo;
    // End of variables declaration//GEN-END:variables
}
